### ISSUE TITLE
redbot is suddenly broken

### ISSUE THREAD

**Issue by psych0d0g** [parkervcp/yolks#185]
yolk has ben running well for quite some time, but when i try to start it now i get an error:
```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:a0b4fe3c05cbaebc9833dec7125fec11d64742d6f32e4f700c50a7c0e9961c9d 
Status: Image is up to date for ghcr.io/parkervcp/yolks:bot_red 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
Traceback (most recent call last):
  File "/home/container/.local/bin/redbot", line 5, in <module>
    from redbot.__main__ import main
ModuleNotFoundError: No module named 'redbot'
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:bot_red 
Digest: sha256:a0b4fe3c05cbaebc9833dec7125fec11d64742d6f32e4f700c50a7c0e9961c9d 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ PATH=$PATH:/home/container/.local/bin redbot pterodactyl --token ${TOKEN} --prefix ${PREFIX}
Traceback (most recent call last):
  File "/home/container/.local/bin/redbot", line 5, in <module>
    from redbot.__main__ import main
ModuleNotFoundError: No module named 'redbot'
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

**Comment by QuintenQVD0** [comment]
and wy yo umake this issue to the yolks repo and not the egg repo? Update your egg, hit reinstall. if it still errors make a egg isssue
